spring:
  datasource:
    password: Dhcc@123!
    username: dhcc
    url: jdbc:postgresql://192.178.62.103:25308/base_db002
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5    # 初始化大小，最小，最大
    minIdle: 5
    maxActive: 40
    maxWait: 6000  # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    validation-query: select 'x'
    useGlobalDataSourceStat: true
    filters: stat,wall
    dbcp2:
      remove-abandoned-on-borrow: true
      remove-abandoned-on-maintenance: true
      remove-abandoned-timeout: 60000
      log-abandoned: true
  redis:

    password:
    lettuce:
      pool:
        max-active: 80000
        max-idle: 800000
        max-wait: 10000
        min-idle: 0
      shutdown-timeout: 100000ms
    timeout: 300000

    database: 0
    cluster:
      nodes:
        - 192.178.61.87:6379
        - 192.178.61.87:9002
        - 192.178.61.87:9003
        - 192.178.61.87:9004
        - 192.178.61.87:9005
        - 192.178.61.87:9006
      max-redirects: 3

  cache:
    redis:
      time-to-live: 600000
  http:
    encoding:
      charset: utf-8
mybatis:
  mapper-locations: classpath:mapper/*.xml        # mybatis配置文件所在路径
server:
  port: 9092
  servlet:
    context-path: /emviewdoctor
swagger:
  enable:true
logging:
  level:
    com:
      dhcens:
        emviewdoctor:
          mapper:
            debug
pagehelper:
  helper-dialect: postgresql
  reasonable: true
  support-methods-arguments: true


